package com.ticketflow.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * A show that has seats for sale.
 *
 * JPA vocabulary:
 *   @Entity   — this class is mapped to a database table.
 *   @Table    — ...specifically the "events" table (without this, JPA would
 *               look for a table called "event", singular).
 *   @Id       — the primary key field.
 *   @GeneratedValue(IDENTITY) — the database assigns the id (our column is
 *               "GENERATED BY DEFAULT AS IDENTITY"), not the application.
 *
 * Lombok vocabulary (annotations that generate boilerplate at compile time):
 *   @Getter @Setter    — generates getName()/setName()/... for every field.
 *   @NoArgsConstructor — generates a public no-argument constructor, which JPA
 *                        requires in order to instantiate the entity.
 */
@Entity
@Table(name = "events")
@Getter
@Setter
@NoArgsConstructor
public class Event {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String venue;

    @Column(name = "starts_at", nullable = false)
    private Instant startsAt;

    @Column(name = "sales_open_at", nullable = false)
    private Instant salesOpenAt;

    @Column(name = "sales_close_at", nullable = false)
    private Instant salesCloseAt;
}