-- V1__initial_schema.sql
-- ===========================================================================
-- The entire starting schema for TicketFlow.
--
-- Guiding principle (CLAUDE.md §3): correctness is enforced by DATABASE
-- CONSTRAINTS, not application code. The unique constraints below are the
-- actual guarantee that a seat is never sold twice. Application-level locking
-- (added in Phase 4) is only there for performance and clean error messages.
--
-- Conventions used here:
--   * table names are plural (events, seats, ...)
--   * every table has a surrogate primary key `id` of type BIGINT
--   * `BIGINT GENERATED BY DEFAULT AS IDENTITY` = Postgres auto-increment.
--     "BY DEFAULT" (not "ALWAYS") lets us also insert an explicit id, which
--     the seed and tests occasionally need.
--   * timestamps are TIMESTAMPTZ ("timestamp with time zone") — stored as UTC,
--     never ambiguous. Java's java.time.Instant maps to this cleanly.
--   * money is stored as an integer number of cents (price_cents), never a
--     float. Floating point and money must never mix.
-- ===========================================================================


-- --- users -----------------------------------------------------------------
-- Auth logic comes in Phase 2, but the table exists now so that seat_holds
-- and bookings can have a real foreign key to it. Note: "user" (singular) is
-- a reserved word in Postgres, so the table is "users".
CREATE TABLE users (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email)
);


-- --- events ---------------------------------------------------------------
CREATE TABLE events (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT        NOT NULL,
    venue          TEXT        NOT NULL,
    starts_at      TIMESTAMPTZ NOT NULL,   -- when the show begins
    sales_open_at  TIMESTAMPTZ NOT NULL,   -- tickets buyable from this moment
    sales_close_at TIMESTAMPTZ NOT NULL    -- ... until this moment
);


-- --- seats ---------------------------------------------------------------
-- One row per physical seat. ~500 of these per event.
CREATE TABLE seats (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    BIGINT  NOT NULL REFERENCES events (id),
    section     TEXT    NOT NULL,          -- e.g. 'Orchestra'
    row_label   TEXT    NOT NULL,          -- e.g. 'A'
    seat_number INTEGER NOT NULL,          -- e.g. 14
    price_cents BIGINT  NOT NULL,
    -- A given physical location belongs to exactly one seat row. This also
    -- stops the seed (or a bug) from inserting the same seat twice.
    CONSTRAINT uq_seats_location UNIQUE (event_id, section, row_label, seat_number),
    CONSTRAINT ck_seats_price_nonneg CHECK (price_cents >= 0)
);
-- We will constantly query "all seats for event X", so index the FK.
CREATE INDEX idx_seats_event_id ON seats (event_id);


-- --- seat_holds --------------------------------------------------------
-- A temporary claim on a seat: "this seat is mine for the next 8 minutes."
-- A hold is RELEASED by setting released_at (either the user paid, or the
-- Phase 5 sweeper expired it). Rows are never deleted — the history is useful.
CREATE TABLE seat_holds (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_id       BIGINT      NOT NULL REFERENCES seats (id),
    hold_group_id UUID        NOT NULL,   -- one checkout = many seats = one group
    user_id       BIGINT      NOT NULL REFERENCES users (id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ NOT NULL,
    released_at   TIMESTAMPTZ             -- NULL = the hold is still active
);

-- ***  THE MOST IMPORTANT LINE IN THIS FILE  ***
-- A partial unique index: "at most one row per seat_id WHERE released_at IS NULL".
-- Translation: a seat can have at most one ACTIVE hold. If two requests race to
-- hold the same seat, the database lets exactly one INSERT succeed and rejects
-- the other with a unique-violation error.
--
-- Why the predicate is ONLY `released_at IS NULL` and not also
-- `expires_at > now()`:  index predicates must be IMMUTABLE, and now() is not.
-- So "expired" is represented by actually writing released_at (Phase 5), not by
-- time passing on its own.
CREATE UNIQUE INDEX uq_seat_holds_one_active_per_seat
    ON seat_holds (seat_id)
    WHERE released_at IS NULL;

-- Look up every seat in a hold group (to release or confirm them together).
CREATE INDEX idx_seat_holds_hold_group ON seat_holds (hold_group_id);

-- The Phase 5 sweeper asks "which active holds are past expires_at?" — support it.
CREATE INDEX idx_seat_holds_active_expiry
    ON seat_holds (expires_at)
    WHERE released_at IS NULL;


-- --- bookings ---------------------------------------------------------
-- A booking is created PENDING at checkout and flipped to CONFIRMED when the
-- payment webhook arrives. total_cents is the price snapshot at checkout time.
CREATE TABLE bookings (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_group_id   UUID        NOT NULL,
    user_id         BIGINT      NOT NULL REFERENCES users (id),
    event_id        BIGINT      NOT NULL REFERENCES events (id),
    status          TEXT        NOT NULL,
    total_cents     BIGINT      NOT NULL,
    idempotency_key TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- The same checkout request retried (same Idempotency-Key header) must not
    -- create a second booking. The DB refuses the duplicate.
    CONSTRAINT uq_bookings_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_bookings_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED'))
);


-- --- booking_seats ---------------------------------------------------
-- Which seats a booking sold. This is the permanent record of a sale.
CREATE TABLE booking_seats (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings (id),
    seat_id    BIGINT NOT NULL REFERENCES seats (id),
    -- ***  THE REAL GUARANTEE  ***
    -- A seat_id can appear here at most once, EVER. Even if every layer above
    -- this has a bug, the database physically cannot record the same seat as
    -- sold twice.
    CONSTRAINT uq_booking_seats_seat UNIQUE (seat_id)
);
CREATE INDEX idx_booking_seats_booking_id ON booking_seats (booking_id);


-- --- webhook_events ------------------------------------------------
-- Every payment-provider webhook we receive is logged here FIRST, before any
-- processing. provider_event_id is the provider's own id for the event.
CREATE TABLE webhook_events (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_event_id TEXT        NOT NULL,
    payload           JSONB       NOT NULL,
    received_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at      TIMESTAMPTZ,
    -- A provider may send the same webhook twice. The second INSERT violates
    -- this constraint, we catch it, and return 200 without reprocessing.
    CONSTRAINT uq_webhook_events_provider_event_id UNIQUE (provider_event_id)
);